---

- name: Add Cloudera Manager yum repository
  yum_repository:
    name: cloudera-manager
    description: Cloudera Manager
    baseurl: "{{ cloudera_manager_repo_url }}"
    gpgkey: "{{ cloudera_manager_repo_key }}"
    gpgcheck: yes
    enabled: yes
